### ISSUE TITLE
Uploading font files outputting wrong destinations

### ISSUE THREAD

**Issue by kylesimmonds** [HubSpot/cos_uploader#10]
I've added Fontello icon-font files into my /files folder to be uploaded through the COS Uploader. The files are uploaded, but are being given the wrong extensions and overwriting the proper files.

The file types are .ttf, .eot, .woff, and .svg.

Whichever one is first, that's the extension the others are being given. Here's the output:

```
Syncing 'files/font/fontello/fontello.svg'
Creation successful for file %s.
You can link to file fontello.svg at http://cdn2.hubspot.net/hub/xxxxxx/font/fontello/fontello.svg
Syncing 'files/font/fontello/fontello.ttf'
Update successful for file %s.
You can link to file fontello.ttf at http://cdn2.hubspot.net/hub/xxxxxx/font/fontello/fontello.svg
Syncing 'files/font/fontello/fontello.woff'
Update successful for file %s.
You can link to file fontello.woff at http://cdn2.hubspot.net/hub/xxxxxx/font/fontello/fontello.svg
Syncing 'files/font/fontello/fontello.eot'
Update successful for file %s.
You can link to file fontello.eot at http://cdn2.hubspot.net/hub/xxxxxx/font/fontello/fontello.svg
```

**Comment by brilee** [comment]
Thanks for the bug report - we'll take a look at it. 

Just to double-check, you're running the latest version, which was released yesterday? Don't think it'll make a difference, but just to be sfae.

**Comment by kylesimmonds** [comment]
@brilee no, I installed this version on Monday. I'll reinstall it and try again.

**Comment by brilee** [comment]
Figured it out. Seems like when checking for previously uploaded versions of the file, we look for it by its extension-less filename. Thus, the uploader just returned the first uploaded version.

The fix (https://github.com/HubSpot/cos_uploader/commit/989f2977b4f2fd48650b338b0e473b3913a65624) looks it up by a different key which does preserve the extension.
