### ISSUE TITLE
File Uploads Not Working

### ISSUE THREAD

**Issue by launchspace** [HubSpot/cos_uploader#11]
Over the past week, I've noticed that file uploads from the 'Files' directory no longer work, and provide output similar to the below.

>Syncing 'files/js/main.js'
>You can link to file main.js at ??? CDN url not found. Check the file manager.

I've had this occur on multiple portals. In all cases, the file is not uploaded. Occurs whether it is a brand new file, or when trying to replace an existing file. Images, javascript, etc. all fail to upload.

**Comment by brilee** [comment]
Thanks for letting us know. I'll take a look at it. Just to double check - is this with the latest version of the syncer?

**Comment by launchspace** [comment]
Yes, latest version.

**Comment by brilee** [comment]
I was able to reproduce and figured out that it was because access tokens had expired.  Deleting your .cos-sync-config.yaml will allow you to reauthorize yourself. 

I'll figure out how to detect this and output a more useful error message.

**Comment by brilee** [comment]
cos uploader is now outputting useful error message

**Comment by launchspace** [comment]
Hi,

This issue has cropped up again - on an existing project, I'm getting the "you can link to file ???". I've deleted the config.yaml file, but it seems that every single time I start the cos_uploader, I need to go through this process again.

**Comment by brilee** [comment]
Hi @launchspace - I'm not 100% sure I'm catching your explanation. I think what you're telling me is that you have multiple portals that you work on, and for each one you have to reauthenticate? If so, there isn't a nice way around that problem, unfortunately.

If that's not the right interpretation - let me know.

**Comment by tone4407** [comment]
I'm having the same issue. How do you delete the config.yaml file?

**Comment by brilee** [comment]
The file is usually hidden - it's named `.cos-sync-config.yaml`. If you show hidden files on your system, you should be able to see it in the same directory that you're working in.

But please also check out our new FTP service - it's in beta, but it'll eventually replace the COS uploader as the recommended method to work offline.  http://designers.hubspot.com/hubspot-ftp

**Comment by tone4407** [comment]
Great! Thanks!

I'm testing out the FTP method now. Logged in via FTPS fine. I'm seeing two folders, 'files' and 'templates'.

The files are uploading fine and displaying in the File Manager. However, when I try to upload my HTML file to the Templates > Custom > Blog folder, I'm getting an error:

<img width="483" alt="screen shot 2015-08-12 at 11 00 29 am" src="https://cloud.githubusercontent.com/assets/8798233/9229156/610e24f4-40e1-11e5-9d84-3181457867d6.png">

Any ideas here?

Also, what does the folder structure look like inside the Templates folder? Where do I put my HTML/CSS/JS?

**Comment by brilee** [comment]
Sorry, I'm not too much of an expert on the FTP server - I'll pass the question along.

**Comment by tone4407** [comment]
Thanks. Another idea, could it be a permissions issue?

**Comment by boulter** [comment]
@tone4407 I'm guessing that the file you're uploading has a syntax error or is trying to include a file that hasn't been uploaded yet. The server should return more descriptive error messages now.

**Comment by Bhramari-P-shetty** [comment]
since from 2 days i'm trying to upload file in my GitHub account, but its showing error. why does its happening? why am i not supposed to upload files

**Comment by ajlaporte** [comment]
Hi @Bhramari-P-shetty, HubSpot has stopped support for this script as of Jan. 1st 2016 (per the readme file).  We would encourage you to take a look at our [HubSpot local development tools](https://designers.hubspot.com/docs/developer-reference/local-development-cms-cli) which provide upload/download capabilities with HubSpot and is the recommended tool for developers.
