### ISSUE TITLE
Uploading files being incorrectly interpreted as HubL

### ISSUE THREAD

**Issue by kylesimmonds** [HubSpot/cos_uploader#13]
I'm trying to upload Snap.svg as an asset, but the uploader thinks part of the script is using HubL.

Here's my error:

```
{u'errors': [],
 u'message': u'There was an error processing your template: TemplateSyntaxException: Error parsing &#39;var i=[];n.toLowerCase()}r.replace(R,function(t,e){e&&i.push(+e)}),e.push([n].concat(i))}),e.toString=n.path.toString,e};n._.svgTransform2string=f,n._.rgTransform=/^[a-z][\\s]*-?\\.?\\d/i,n._.transform2matrix=h,n._unit2px=m;k.doc.contains||k.doc.compareDocumentPosition?function(t,e){var n=9==t.nodeType?t.documentElement:t,r=e&&e.parentNode;return t==r||!(!r||1!=r.nodeType||!(n.contains?n.contains(r):t.compareDocumentPosition&&16&t.compareDocumentPosition(r)))}:function(t,e){if(e)for(;e;)if(e=e.parentNode,e==t)return!0;return!1};n._.getSomeDefs=d,n._.getSomeSVG=p,n.select=function(t){return t=T(t).replace(/([^\\\\]):/g,&quot;$1\\\\:&quot;),S(k.doc.querySelector(t))},n.selectAll=function(t){for(var e=k.doc.querySelectorAll(t),r=(n.set||Array)(),i=0;i&lt;e.length;i++)r.push(S(e[i]));return r},setInterval(function(){for(var t in H)if(H[_](t)){var e=H[t],n=e.node;(&quot;svg&quot;!=e.type&&!n.ownerSVGElement||&quot;svg&quot;==e.type&&(!n.parentNode||&quot;ownerSVGElement&quot;in n.parentNode&&!n.ownerSVGElement))&&delete H[t]&#39;: syntax error at position 6, encountered &#39;i&#39;, expected &#39;}&#39;',
 u'succeeded': False}
```

Not sure what needs to be done to fix this, but the Uploader needs to be able to differentiate between two brackets being HubL or another language.

**Comment by brilee** [comment]
Hi Kyle - I'm currently on vacation; will get back to this next week. Thanks for the report!

**Comment by brilee** [comment]
When you say you're trying to upload 'snap.svg' as an asset, are you adding a hubspot-metadata section and all that jazz? It seems to me that a .svg file should be uploaded as-is to the file manager, without being interpreted in any way.

**Comment by kylesimmonds** [comment]
Sorry, I meant Snap.svg.js, the JS library for SVGs.

**Comment by brilee** [comment]
Can you copy the hubspot-metadata section you're using?

**Comment by kylesimmonds** [comment]
```
/*
[hubspot-metadata]
{
  "category": "asset",
  "creatable": false,
  "path": "custom/page/lightpaper/script.js"
}
[end-hubspot-metadata]
*/
```

**Comment by brilee** [comment]
I spoke with some of our other devs about coded files. It turns out that we allow certain kinds of jinja to appear in .js files, so we have to interpret them as such. That leads to the unfortunate side effect that your .js files can't have {{...}} in them anywhere - which minified files tend to have.

Since this is an external library you probably aren't modifying, you can instead upload it to the file manager and link to the cdn url.

**Comment by kylesimmonds** [comment]
That's what I ended up doing. It seems wrong to put assets like JS and CSS in the File Manager, since those files should be editable within the Design Manager.

But since my original question is answered, I'll close this.

**Comment by IanRMcNair** [comment]
There's another workaround: You can echo the `{{`/`{%`/`{#` like so:

    {{ "{{" }}

A little ugly, but it works. I sometimes have to do this for Modernizr.

**Comment by kylesimmonds** [comment]
Good point, Modernizr has thrown the same error for me before. Is this not a capability that can be built into the uploader? I realize you still need to be able to insert jinja, but if the content of `{{}}` isn't valid jinja, it should be assumed it's just JavaScript.

**Comment by jaredstehler** [comment]
You may also be able to wrap the whole file in {% raw %} ... {% endraw %} tags
